### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by wale-prog** [wale-prog/space-travellers#48]
Hello,
We are two on this project and here is the [link ](https://github.com/wale-prog/space-travellers/projects/1)to the GitHub project

**Comment by keroloussamy** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] Kindly add both of you to the group tasks on the cards.

![image](https://user-images.githubusercontent.com/35535130/179574041-755b5e3d-eb3e-48c3-b797-7c98ab17e6b1.png)



Cheers and Happy coding!👏👏👏

**Comment by wale-prog** [comment]
Done, thanks.

**Comment by Wes-Isaac** [comment]
Hi @wale-prog @shahnawaza75, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Kanban board setup properly.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by wale-prog** [comment]
Thank you for the review.
